channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake-minimal==7.32.4
  - matplotlib==3.8.0
  - pandas==2.1.2
  - networkx==3.2
  - numpy==1.24.4
  - scikit-learn==1.3.2
  - graphviz
  - seaborn==0.13.0
  - gdown==4.7.1
  - openmatrix==0.3.5
  - pip==23.3.1
  - pip:
    - cell-flower==0.1.1